### ISSUE TITLE
Modify Readme 

### ISSUE THREAD

**Issue by VGandhi27** [kcp-dev/infra#41]
Need to mention the project in detail like

1. Introduction
2. Data flow
3. modules implemented
4. Algorithm used
5. Contribution Guidelines etc

**Comment by xrstf** [comment]
This issue may have been opened accidentally. I'm going to close it now, but feel free to open a new issue with a more descriptive title or ask any questions in Kubernetes Slack :)

**Comment by VGandhi27** [comment]
Thank you
